my:
   greeting: balagi-config-server-test_GREETING
   list:
      value: One,Two,Three
my.map.value: {'key1':1,'key2':2,'key3':3}
app:
   name: My app
   description: Welcome to ${app.name}

db:
   connectionurl: jdbc:mysql://localhost:3306/springbootdb
   driverclassname: com.mysql.jdbc.Driver
   username: root
   password: root
